### ISSUE TITLE
Namespace issue

### ISSUE THREAD

**Issue by typoworx-de** [Lusitanian/PHPoAuthLib#488]
Some files abuse the php-namespace conventions. Usually the Namespace should be the first after php-tag. Some files have the namespace preceeding with two linebreaks breaking the functionality of PSR-4 Autoloader.

Example:
[OAuth/Common/Http/Uri/UriFactory.php](https://github.com/Lusitanian/PHPoAuthLib/blob/master/src/OAuth/Common/Http/Uri/UriFactory.php#L3)

```php
<?php

namespace OAuth\Common\Http\Uri;

use RuntimeException;
```

It should look like this:

```php
<?php
namespace OAuth\Common\Http\Uri;

use RuntimeException;
```

**Comment by PeeHaa** [comment]
> Some files abuse the php-namespace conventions.

What files and what "php-namespace" conventions?

> Usually the Namespace should be the first after php-tag.  Some files have the namespace preceeding with two linebreaks breaking the functionality of PSR-4 Autoloader.

PSR4 says nothing about linebreaks (nor does PSR0) AFAIK. And it certainly won't break the functionality of PSR-4 Autoloader.

Do you have a specific issue? Because it feels to me that you are asking about a problem without explaining the actual problem.
